Repository edera-dev/krata, pull requests merged in 2024-04, with the labels that each got.

#18 fix: service files should have kratanet depend on kratad
  resources/openrc/kratad
  resources/openrc/kratanet
  resources/systemd/kratanet.service
Labels: enhancement

#23 chore: release workflow fixes to improve utilization and fix checks
  .github/workflows/check.yml
  .github/workflows/client.yml
  .github/workflows/kernel.yml
  .github/workflows/os.yml
  .github/workflows/release-plz.yml
  .github/workflows/server.yml
Labels: bug, enhancement

#49 fix: use alpine rust triplets when building on alpine
  hack/build/cargo.sh
  hack/build/target.sh
Labels: bug

#64 feat: implement oci image progress
  Cargo.lock
  Cargo.toml
  crates/ctl/Cargo.toml
  crates/ctl/src/cli/destroy.rs
  crates/ctl/src/cli/launch.rs
  crates/ctl/src/cli/watch.rs
  crates/ctl/src/console.rs
  crates/daemon/Cargo.toml
  crates/daemon/bin/daemon.rs
  crates/daemon/src/event.rs
  crates/daemon/src/lib.rs
  crates/daemon/src/oci.rs
  crates/krata/proto/krata/v1/control.proto
  crates/krata/src/v1/common.rs
  crates/krata/src/v1/control.rs
  crates/network/src/autonet.rs
  crates/oci/examples/squashify.rs
  crates/oci/src/compiler.rs
  crates/oci/src/fetch.rs
  crates/oci/src/lib.rs
  crates/oci/src/progress.rs
  crates/oci/src/registry.rs
  crates/runtime/Cargo.toml
  crates/runtime/examples/squashify.rs
  crates/runtime/src/launch.rs
  crates/runtime/src/lib.rs
Labels: enhancement

#71 feat: idm snooping
  crates/ctl/src/cli/idm_snoop.rs
  crates/ctl/src/cli/mod.rs
  crates/daemon/src/control.rs
  crates/daemon/src/idm.rs
  crates/krata/build.rs
  crates/krata/proto/krata/bus/idm.proto
  crates/krata/proto/krata/v1/control.proto
  crates/krata/src/bus/idm.rs
  crates/krata/src/bus/mod.rs
  crates/krata/src/idm/client.rs
  crates/krata/src/idm/mod.rs
  crates/krata/src/lib.rs
Labels: enhancement

#72 feat: basic kratactl top command
  Cargo.lock
  Cargo.toml
  crates/ctl/Cargo.toml
  crates/ctl/src/cli/mod.rs
  crates/ctl/src/cli/top.rs
  crates/ctl/src/format.rs
  crates/ctl/src/lib.rs
  crates/ctl/src/metrics.rs
  crates/daemon/src/idm.rs
  crates/krata/src/idm/client.rs
  crates/runtime/src/channel.rs
Labels: enhancement

#70 feat: oci packer can now use mksquashfs if available
  Cargo.lock
  Cargo.toml
  DEV.md
  FAQ.md
  crates/ctl/src/cli/launch.rs
  crates/daemon/src/reconcile/guest.rs
  crates/guest/src/init.rs
  crates/krata/src/launchcfg.rs
  crates/oci/Cargo.toml
  crates/oci/examples/squashify.rs
  crates/oci/src/cache.rs
  crates/oci/src/compiler.rs
  crates/oci/src/lib.rs
  crates/oci/src/packer.rs
  crates/oci/src/progress.rs
  crates/runtime/src/launch.rs
  hack/dist/apk.sh
  hack/dist/deb.sh
  hack/kernel/build.sh
  kernel/krata-x86_64.config
Labels: enhancement

#85 feat: oci compliance work
  crates/ctl/src/cli/destroy.rs
  crates/ctl/src/cli/launch.rs
  crates/ctl/src/cli/mod.rs
  crates/ctl/src/cli/pull.rs
  crates/ctl/src/cli/watch.rs
  crates/ctl/src/console.rs
  crates/ctl/src/lib.rs
  crates/ctl/src/metrics.rs
  crates/ctl/src/pull.rs
  crates/daemon/src/control.rs
  crates/daemon/src/event.rs
  crates/daemon/src/lib.rs
  crates/daemon/src/oci.rs
  crates/daemon/src/reconcile/guest.rs
  crates/krata/proto/krata/v1/common.proto
  crates/krata/proto/krata/v1/control.proto
  crates/network/src/autonet.rs
  crates/oci/examples/squashify.rs
  crates/oci/src/assemble.rs
  crates/oci/src/compiler.rs
  crates/oci/src/fetch.rs
  crates/oci/src/lib.rs
  crates/oci/src/packer.rs
  crates/oci/src/packer/backend.rs
  crates/oci/src/packer/cache.rs
  crates/oci/src/packer/mod.rs
  crates/oci/src/packer/service.rs
  crates/oci/src/progress.rs
  crates/oci/src/registry.rs
  crates/oci/src/vfs.rs
  crates/runtime/src/cfgblk.rs
  crates/runtime/src/launch.rs
  crates/runtime/src/lib.rs
Labels: enhancement

#88 feat: oci tar format, bit-perfect disk storage for config and manifest, concurrent image pulls
  Cargo.lock
  crates/ctl/src/cli/launch.rs
  crates/ctl/src/cli/pull.rs
  crates/daemon/Cargo.toml
  crates/daemon/src/control.rs
  crates/daemon/src/reconcile/guest.rs
  crates/krata/proto/krata/v1/common.proto
  crates/krata/proto/krata/v1/control.proto
  crates/oci/examples/squashify.rs
  crates/oci/src/assemble.rs
  crates/oci/src/fetch.rs
  crates/oci/src/lib.rs
  crates/oci/src/packer/backend.rs
  crates/oci/src/packer/cache.rs
  crates/oci/src/packer/mod.rs
  crates/oci/src/packer/service.rs
  crates/oci/src/progress.rs
  crates/oci/src/registry.rs
  crates/oci/src/schema.rs
  crates/runtime/src/cfgblk.rs
  crates/runtime/src/launch.rs
Labels: enhancement

#95 feat: oci concurrency improvements
  crates/ctl/src/cli/launch.rs
  crates/ctl/src/cli/pull.rs
  crates/ctl/src/pull.rs
  crates/daemon/src/control.rs
  crates/daemon/src/lib.rs
  crates/daemon/src/oci.rs
  crates/krata/proto/krata/v1/control.proto
  crates/oci/examples/squashify.rs
  crates/oci/src/assemble.rs
  crates/oci/src/fetch.rs
  crates/oci/src/name.rs
  crates/oci/src/packer/backend.rs
  crates/oci/src/packer/cache.rs
  crates/oci/src/packer/mod.rs
  crates/oci/src/packer/service.rs
  crates/oci/src/progress.rs
  crates/oci/src/registry.rs
  crates/oci/src/vfs.rs
Labels: enhancement

#114 feat: pci passthrough
  Cargo.lock
  Cargo.toml
  crates/ctl/src/cli/launch.rs
  crates/ctl/src/cli/list_devices.rs
  crates/ctl/src/cli/mod.rs
  crates/daemon/Cargo.toml
  crates/daemon/src/config.rs
  crates/daemon/src/control.rs
  crates/daemon/src/devices.rs
  crates/daemon/src/lib.rs
  crates/daemon/src/reconcile/guest/mod.rs
  crates/daemon/src/reconcile/guest/start.rs
  crates/guest/Cargo.toml
  crates/guest/src/init.rs
  crates/krata/proto/krata/v1/common.proto
  crates/krata/proto/krata/v1/control.proto
  crates/oci/src/name.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/cfgblk.rs
  crates/runtime/src/launch.rs
  crates/xen/xencall/src/lib.rs
  crates/xen/xencall/src/sys.rs
  crates/xen/xenclient/Cargo.toml
  crates/xen/xenclient/examples/boot.rs
  crates/xen/xenclient/examples/pci.rs
  crates/xen/xenclient/src/error.rs
  crates/xen/xenclient/src/lib.rs
  crates/xen/xenclient/src/pci.rs
  crates/xen/xenclient/src/x86.rs
  hack/dist/bundle.sh
  hack/dist/systar.sh
  hack/kernel/build.sh
  kernel/krata-x86_64.config
Labels: enhancement
